### ISSUE TITLE
CDK Watch

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#1]
## Description

CDK Watch is a new feature of the AWS CDK which allows developers to quickly iterate on development stacks. CDK Watch performs quick updates to AWS Lambda function code and ECS images in response to changes in the application code. CDK Watch has an extensible design, which means that it will be possible to support additional AWS resources such as API Gateway models, Step Function workflows, and more.

## Roles

| Role                | User
|---------------------|------------------------------
| Author(s)           | @offbyone, @skinny85
| API Bar Raiser      | @eladb
| Stakeholders        | `TBD`

> See [RFC Process](https://github.com/aws/aws-cdk-rfcs#rfc-process) for details

## Workflow

- [x] Tracking issue created (label: `status/proposed`)
- [x] API bar raiser assigned (ping us at
  [#aws-cdk-rfcs](https://cdk-dev.slack.com/archives/C025ZFGMUCD) if needed)
- [x] Kick off meeting
- [x] RFC pull request submitted (label: `status/review`)
- [x] Community reach out (via Slack and/or Twitter)
- [x] API signed-off (label `api-approved` applied to pull request)
- [x] Final comments period (label: `status/final-comments-period`)
- [x] Approved and merged (label: `status/approved`)
- [x] Execution plan submitted (label: `status/planning`)
- [x] Plan approved and merged (label: `status/implementing`)
- [x] Implementation complete (label: `status/done`)

---

> Author is responsible to progress the RFC according to this checklist, and
apply the relevant labels to this issue so that the RFC table in README gets
updated.

**Comment by eladb** [comment]
https://aws-blog.de/2020/07/cdk-speedster-fast-lambda-deployment.html

**Comment by kirkness** [comment]
In case you are looking for this feature, I've created a wee lib to make this possible: https://github.com/teamplanes/cdk-watch

We are using it on a few projects and it has sped up developer workflows/feedback-loops dramatically.

**Comment by eladb** [comment]
Some related projects: 
* https://github.com/teamplanes/cdk-watch
* https://serverless-stack.com

**Comment by alexpulver** [comment]
@eladb @skinny85 can newly released CloudFormation feature to keep failed stack deployments abd retry/update them be useful for this capability in addition to API-based updates? https://aws.amazon.com/blogs/aws/new-for-aws-cloudformation-quickly-retry-stack-operations-from-the-point-of-failure/

**Comment by skinny85** [comment]
> @eladb @skinny85 can the newly released CloudFormation feature to keep failed stack deployments abd retry/update them be useful for this capability in addition to API-based updates? https://aws.amazon.com/blogs/aws/new-for-aws-cloudformation-quickly-retry-stack-operations-from-the-point-of-failure/

Yes. This was already implemented in https://github.com/aws/aws-cdk/pull/16293 as a switch in the `cdk` CLI, and will be turned on by default for deployments done with the `--hotswap` option (PR in flight: https://github.com/aws/aws-cdk/pull/15748).

**Comment by Chriscbr** [comment]
Closing this since the feature seems to be successfully launched. 🙂
