### ISSUE TITLE
Compatibility Assurance Strategy

### ISSUE THREAD

**Issue by iliapolo** [aws/aws-cdk-rfcs#110]
|PR|Champion|
|--|--------|
|[#111](https://github.com/aws/aws-cdk-rfcs/pull/111) |   @eladb       |

## Description

Devise a strategy for assuring we keep our CLI vs Framework Compatibility promises to customers:

- New CLI versions should always support older framework versions.
- New Framework versions might require a CLI upgrade.

  > In which case, we display an error message instructing the user which version to upgrade to.  

## Progress

- [x] Tracking Issue Created
- [x] RFC PR Created 
- [x] Core Team Member Assigned 
- [x] Initial Approval / Final Comment Period
- [x] Ready For Implementation
- [ ] Resolved
