### ISSUE TITLE
New CDK Major Version

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#118]
|PR|Champion|
|--|--------|
|# |        |

## Description

The purpose of this RFC is to describe the process and implications of releasing a new major version for the AWS CDK.

### Things to consider

- [ ] Release process
- [ ] Long-term support for previous major versions
- [ ] Regular clean ups across major versions such as:
  - [ ] Remove all deprecated APIs
  - [ ] Reset all [feature flags](https://github.com/aws/aws-cdk/blob/master/design/feature-flags.md)

### v2.0 Candidates

- [ ] aws/aws-cdk#1687
- [ ] aws/aws-cdk#5067 - get rid of type unions everywhere (they suck in statically typed languages)
- [ ] https://github.com/aws/aws-cdk/issues/3930
- [ ] [rename construct "id" to "ns"](https://github.com/aws/aws-cdk/issues/3203)
- [ ] Remove backwards compatibility support for docker assets with parameters
- [ ] Consider renaming reserved keywords per jsii recommendation (https://github.com/aws/jsii/commit/5389def583160d6e06bb399704ff4cce9c8ef13a)

## Progress

- [x] Tracking Issue Created
- [ ] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by eladb** [comment]
Duplicate with #79
