### ISSUE TITLE
Many CDK alternative to Mono CDK

### ISSUE THREAD

**Issue by CaerusKaru** [aws/aws-cdk-rfcs#131]
|PR|Champion|
|--|--------|
|#132 |        |

## Description

There are some key concerns with #6 and its accompanying RFC #122. Namely, it does not totally solve the issue that it claims to solve. Further, it creates issues for users hoping to use the library from a limited environment like Lambda, which has a strict upload size limit.

The proposal is to create a limited number of AWS CDK packages, published by grouping L2 constructs under the categories they're listed under on the AWS Console (or another naming convention that we agree on). The L1 constructs _will_ be moved into a singular package along with all other CloudFormation utilities. The core utilities will then be abstracted to a separate core package that can be consumed independent of the CDK (for GitHub Actions for instance).

## Progress

- [x] Tracking Issue Created
- [x] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by CaerusKaru** [comment]
Closing in favor of comments on  #6 and #122
