### ISSUE TITLE
CloudFront Module Redesign

### ISSUE THREAD

**Issue by njlynch** [aws/aws-cdk-rfcs#171]
|PR|Champion|
|--|--------|
|[#174](/aws/aws-cdk-rfcs/pull/174) |  @iliapolo  |

## Description

See https://github.com/aws/aws-cdk/issues/572 for some background.
> There's a lot we can do in order to make it friendlier, less error-prone and less flat and declarative. At the moment, it's basically "leaking" the low level API provided by CloudFormation.

## Progress

- [x] Tracking Issue Created
- [x] RFC PR Created 
- [x] Core Team Member Assigned
- [x] Initial Approval / Final Comment Period
- [x] Ready For Implementation
- [x] Resolved

**Comment by iliapolo** [comment]
@njlynch @rix0rrr @skinny85 

This is what I had in mind:

```typescript
// 90th percentile: only default behavior
new cloudfront.Distribution(this, 'Distribution', {
  defaultBehavior: {
    origin: cloudfront.Origin.fromBucket(myBucket, {}),
    allowedMethods: ALL,
    compress: true
  }
})

// 10th percentile: 1 default behavior, 3 custom behaviors

// at construction
new cloudfront.Distribution(this, 'Distribution', {
  defaultBehavior: {
    origin: cloudfront.Origin.fromBucket(myBucket),
    allowedMethods: ALL,
    compress: true
  },
  additionalBehaviors: {
    '/api/*': {
      origin: cloudfront.Origin.fromHttpServer({
        domainName: 'www.example.com',
        protocolPolicy: OriginProtocolPolicy.HTTPS_ONLY,
      }),
      allowedMethods: ALL,
      compress: true
    },
    '/api/_admin/*': {
      origin: cloudfront.Origin.fromHttpServer({
        domainName: 'www.example.com',
        protocolPolicy: OriginProtocolPolicy.HTTPS_ONLY,
      }),
      allowedMethods: [GET],
      compress: false
    },
    '/assets/*': {
      origin: cloudfront.Origin.fromBucket(myBucket),
      allowedMethods: ALL,
      compress: true
    }
  }
})

// post construction
const distribution = new cloudfront.Distribution(this, 'Distribution', {
  defaultBehavior: {
    origin: cloudfront.Origin.fromBucket(myBucket),
    allowedMethods: ALL,
    compress: true
  }
})

distribution.addBehavior('/api/*', {
  origin: cloudfront.Origin.fromHttpServer({
    domainName: 'www.example.com',
    protocolPolicy: OriginProtocolPolicy.HTTPS_ONLY,
  }),
  allowedMethods: ALL,
  compress: true
});

distribution.addBehavior('/api/_admin/*', {
  origin: cloudfront.Origin.fromHttpServer({
    domainName: 'www.example.com',
    protocolPolicy: OriginProtocolPolicy.HTTPS_ONLY,
  }),
  allowedMethods: [GET],
  compress: false
});

distribution.addBehavior('/assets/*', {
  origin: cloudfront.Origin.fromHttpServer(myBucket),
  allowedMethods: ALL,
  compress: true
});
```

Basically flipping the model and only thinking about behaviors rather than origins. An origin is just a property of a specific behavior (which is actually how CFN [models](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-cachebehavior.html#cfn-cloudfront-distribution-cachebehavior-targetoriginid) it as well)

Notice that in the example above we have multiple behaviors that map to the same origin, creating a somewhat awkward N:1 mapping. Is it though? 

`/api/*` and `/api/_admin/*` map to the same http server, but i think that makes sense from a usage perspective, rather than having 1 origin with multiple behaviors. 

Thoughts?

**Comment by njlynch** [comment]
Implementation is being tracked in https://github.com/aws/aws-cdk/milestone/5
