### ISSUE TITLE
AppSync Mapping Template Object Model

### ISSUE THREAD

**Issue by duarten** [aws/aws-cdk-rfcs#175]
|PR|Champion|
|--|--------|
|#177 |        |

## Description

AppSync Mapping Templates apply complex transformations to incoming GraphQL requests and to the responses from the data sources. There are multiple facilities that AppSync exposes to help write them, such as variable declaration, access to a Cognito identity, etc. In the CDK, as well as in the console, they're mostly written as raw strings. We propose here a well-defined, typed interface, to make writing mapping templates less error prone, and to make the AppSync facilities discoverable.

## Progress

I've been implementing the RFC contents for my company to leverage; currently modeled mostly DynamoDB APIs.

- [x] Tracking Issue Created
- [x] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by MrArnoldPalmer** [comment]
Since JS resolvers are coming, we put this on hold. Let's reopen when we have another design outlined.

**Comment by mrgrain** [comment]
Superceded by reality. We appreciate the effort that has gone into this proposal. Marking an RFCs as rejected is not a one-way door. If you have made substantial changes to the proposal, please open a new issue/RFC. You might also consider raising a PR to [aws/aws-cdk](https://github.com/aws/aws-cdk/) directly or self-publishing to Construct Hub.
