### ISSUE TITLE
Removal of the "constructs" compatibility layer (v2.0)

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#192]
|PR|Champion|
|--|--------|
|#195 | @RomainMuller         |

## Description

As part of [v2.0](https://github.com/aws/aws-cdk-rfcs/issues/156) we would like to deprecate the compatibility layer we have in @aws-cdk/core for the [constructs](https://github.com/aws/constructs) library.

## Progress

- [x] Tracking Issue Created
- [x] RFC PR Created 
- [x] Core Team Member Assigned 
- [x] Initial Approval / Final Comment Period
- [x] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by eladb** [comment]
This is completed in the v2.0 branch of the CDK. Yeah!
