### ISSUE TITLE
Fixing of type unions

### ISSUE THREAD

**Issue by RomainMuller** [aws/aws-cdk-rfcs#193]
|PR|Champion|
|--|--------|
|#194 | @RomainMuller |

## Description

Usage of TypeScript type unions has proven to be a source of problems when representing APIs in statically typed languages, such as Java and C#. This proposal is about fixing type unions to address these developer experience issues.

This is a candidate change for [v2](https://github.com/aws/aws-cdk-rfcs/issues/79)

## Progress

- [x] Tracking Issue Created
- [x] RFC PR Created 
- [x] Core Team Member Assigned 
- [x] Initial Approval / Final Comment Period
- [x] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by mrgrain** [comment]
There is a significant proposal, but no current owner. Closing as stale.
