### ISSUE TITLE
JSII Go Support

### ISSUE THREAD

**Issue by SoManyHs** [aws/aws-cdk-rfcs#204]
https://github.com/aws/aws-cdk/issues/547

|PR|Champion|
|--|--------|
|#206 |    Hsing-Hui Hsu @SoManyHs, Mitch Valine @MrArnoldPalmer   |

## Description

Go language support is the number one most-requested feature in the CDK. This is a proposal for the design and implementation of a Go language binding.

See: https://github.com/aws/aws-cdk/issues/547

## Progress

- [x] Tracking Issue Created
- [x] RFC PR Created 
- [x] Core Team Member Assigned 
- [x] Initial Approval / Final Comment Period
- [x] Ready For Implementation
    
    - [x] implementation issue 1
- [x] Resolved

**Comment by xrn** [comment]
@SoManyHs can we mark the checkbox "Core Team Member Assigned" ^^?

**Comment by xrn** [comment]
@SoManyHs @MrArnoldPalmer - I see that PR is merged. This means in https://github.com/aws/aws-cdk-rfcs/blob/master/README.md we can move to Approved and we are just waiting for the Implementation? Thanks for the answer

**Comment by MrArnoldPalmer** [comment]
@xrn table is updated here https://github.com/aws/aws-cdk-rfcs/pull/274.

This is supposed to happen automatically but we need to fix our action.

**Comment by SoManyHs** [comment]
https://github.com/aws/aws-cdk-rfcs/issues/206 was merged! 🥳
