### ISSUE TITLE
CDK Explorer Roadmap

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#21]
|PR|Champion|
|--|--------|
|# |        |

## Description

- [ ] Jump to code
- [ ] Deploy
- [ ] Diff visualization
- [ ] Watch
- [ ] Permissions View (https://github.com/awslabs/aws-cdk-rfcs/issues/20)
- [ ] Filter out system constructs (like `Parameters`)
- [ ] Showing types for L2 constructs (merging with "Resource")
- [ ] Deep linking resources to console (cross account support using CI/CD deployment roles)
- [ ] Surface drift detection (https://github.com/awslabs/aws-cdk-rfcs/issues/24)

## Progress

- [x] Tracking Issue Created
- [ ] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by pgollucci** [comment]
Any more thoughts here?
