### ISSUE TITLE
ECS Patterns Service Builder

### ISSUE THREAD

**Issue by nathanpeck** [aws/aws-cdk-rfcs#219]
|PR|Champion|
|--|--------|
|https://github.com/aws/aws-cdk-rfcs/pull/221 |    @MrArnoldPalmer     |

## Description

A new ECS pattern for a `Service` class which supports extensions via `Service.add()` for enabling more complex features on ECS services

## Progress

- [x] Tracking Issue Created
- [x] RFC PR Created 
- [x] Core Team Member Assigned 
- [x] Initial Approval / Final Comment Period
- [x] Ready For Implementation
    
    - [ ] implementation issue 1
- [x] Resolved

**Comment by nathanpeck** [comment]
@MrArnoldPalmer Can I get you or someone else from the core team to look at this RFC referenced in the PR and see if its ready for initial approval?

**Comment by mrgrain** [comment]
Ended up as a separate package: https://github.com/cdklabs/cdk-ecs-service-extensions
