### ISSUE TITLE
Migration path for EKS Developer Preview

### ISSUE THREAD

**Issue by iliapolo** [aws/aws-cdk-rfcs#244]
|PR|Champion|
|--|--------|
|#245 |   @eladb      |

## Description

When we introduce breaking changes to `experimental` libraries that require resource replacements,
or in general are considered highly intrusive, we should provide a clear migration path.

## Progress

- [x] Tracking Issue Created
- [X] RFC PR Created 
- [X] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved
