### ISSUE TITLE
CDK Metadata v2

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk-rfcs#253]
|PR|Champion|
|--|--------|
|#254 |  @nija-at      |

## Description

We need to overhaul CDK metadata for v2.

## Progress

- [x] Tracking Issue Created
- [x] RFC PR Created 
- [x] Core Team Member Assigned 
- [x] Initial Approval / Final Comment Period
- [x] Ready For Implementation
    
    - [ ] implementation issue 1
- [x] Resolved
