### ISSUE TITLE
Kinesis Data Firehose Delivery Stream L2

### ISSUE THREAD

**Issue by BenChaimberg** [aws/aws-cdk-rfcs#340]
## Description

Support Firehose Delivery Stream as an L2 construct in the framework library.

The `aws-kinesisfirehose` construct library allows you to create Amazon Kinesis Data Firehose delivery streams and destinations with just a few lines of code. As with most construct libraries, you can also easily define permissions and metrics using a simple API.

## Roles

| Role                | User
|---------------------|------------------------------
| Author(s)           | @madeline-k @otaviomacedo @BenChaimberg
| API Bar Raiser      | @rix0rrr

> See [RFC Process](https://github.com/aws/aws-cdk-rfcs#rfc-process) for details

## Workflow

- [x] Tracking issue created (label: `status/proposed`)
- [x] API bar raiser assigned (ping us at [#aws-cdk-rfcs](https://cdk-dev.slack.com/archives/C025ZFGMUCD) if needed)
- [x] Kick off meeting
- [x] RFC pull request submitted (label: `status/review`)
- [ ] Community reach out (via Slack and/or Twitter)
- [x] API signed-off (label `api-approved` applied to pull request)
- [x] Final comments period (label: `status/final-comments-period`)
- [x] Approved and merged (label: `status/approved`)
- [ ] Execution plan submitted (label: `status/planning`)
- [x] Plan approved and merged (label: `status/implementing`)
- [x] Implementation complete (label: `status/done`)

---

> Author is responsible to progress the RFC according to this checklist, and
apply the relevant labels to this issue so that the RFC table in README gets
updated.

**Comment by eladb** [comment]
@madeline-k @otaviomacedo @BenChaimberg I've updated this issue according to the new RFC process template. Please take a look at the new process description.

Can you also please take a look at the updated RFC template and align your RFC to it (should be quite similar).

@rix0rrr I've assigned you as the API Bar Raiser for this RFC. Your job is to approve the public API described in the RFC. Once approved, please slap an "api-approved" label to the RFC PR.

**Comment by BenChaimberg** [comment]
Implementation tracked in [aws/aws-cdk milestone 16](https://github.com/aws/aws-cdk/milestone/16)
