### ISSUE TITLE
Construct Library for Contributor Insights Rules

### ISSUE THREAD

**Issue by abrahcoh** [aws/aws-cdk-rfcs#362]
## Description

Contributor Insights is an AWS service provided by CloudWatch that allows the user to analyze high cardinality data from their cloud components. 

With an L2 Construct for Contributor Insights Rules, users can create rules by leveraging their IDEs and OOP principles. Instead of making rule bodies either manually or by various scripts, which incurs significant user time, users can create rule bodies using rule body builders provided by the L2 Construct. This will provide the user the ability to leverage their IDEs for navigating rule body formats and rule body field data types, which will significantly reduce development effort. Furthermore, this will also provide a heavy decrease in error detection and error correction time, as the user will no longer have to wait for Cloud Formation to be alerted of errors in their rules and can instead get immediate and granular feedback from the CDK. 

## Roles

| Role                | User
|---------------------|------------------------------
| Proposed by         | @abrahcoh
| Author(s)           | @abrahcoh
| API Bar Raiser      | @madeline-k 
| Stakeholders        | @alias, @alias, @alias

## Workflow

- [x] Tracking issue created (label: `status/proposed`)
- [x] API bar raiser assigned (ping us at [#aws-cdk-rfcs](https://cdk-dev.slack.com/archives/C025ZFGMUCD) if needed)
- [x] Kick off meeting
- [x] RFC pull request submitted (label: `status/review`)
- [ ] Community reach out (via Slack and/or Twitter)
- [ ] API signed-off (label `api-approved` applied to pull request)
- [ ] Final comments period (label: `status/final-comments-period`)
- [ ] Approved and merged (label: `status/approved`)
- [ ] Execution plan submitted (label: `status/planning`)
- [ ] Plan approved and merged (label: `status/implementing`)
- [ ] Implementation complete (label: `status/done`)

**Comment by awsmjs** [comment]
Closing this ticket. We believe the functionality is beneficial, but does not intersect with the core framework and should be vended and maintained separately.
