### ISSUE TITLE
CDK environment setup for platform/system administrators

### ISSUE THREAD

**Issue by skinny85** [aws/aws-cdk-rfcs#419]
## Description

CDK is tricky to use in restricted environments where there is a split between the platform/system administrator teams, and the application development teams who use CDK.

This RFC proposes a set of features for dealing with that problem.

## Roles

| Role                | User
|---------------------|------------------------------
| Proposed by         | @skinny85
| Author(s)           | @skinny85
| API Bar Raiser      | @rix0rrr
| Stakeholders        | @cgarvis, @addihorowitz, @rix0rrr

> See [RFC Process](https://github.com/aws/aws-cdk-rfcs#rfc-process) for details

## Workflow

- [x] Tracking issue created (label: `status/proposed`)
- [x] API bar raiser assigned (ping us at [#aws-cdk-rfcs](https://cdk-dev.slack.com/archives/C025ZFGMUCD) if needed)
- [x] Kick off meeting
- [x] RFC pull request submitted (label: `status/review`)
- [ ] Community reach out (via Slack and/or Twitter)
- [ ] API signed-off (label `api-approved` applied to pull request)
- [ ] Final comments period (label: `status/final-comments-period`)
- [ ] Approved and merged (label: `status/approved`)
- [ ] Execution plan submitted (label: `status/planning`)
- [ ] Plan approved and merged (label: `status/implementing`)
- [ ] Implementation complete (label: `status/done`)

---

> Author is responsible to progress the RFC according to this checklist, and
apply the relevant labels to this issue so that the RFC table in README gets
updated.

**Comment by skinny85** [comment]
@rix0rrr I've assigned you as the API bar raiser on this one, let me know if you disagree.

**Comment by skinny85** [comment]
Pull Request with the RFC: https://github.com/aws/aws-cdk-rfcs/pull/421.
