### ISSUE TITLE
AWS Ground Station L2 Constructs

### ISSUE THREAD

**Issue by kochie** [aws/aws-cdk-rfcs#434]
## Description

AWS Ground Station allows end users to communicate with satellites in orbit. This construct library allows CDK users to create the infrastructure to easily communicate with satellites.

The aim of this library is to provide an even easier way of defining the Mission Profiles needed to connect with satellites by providing constructs with more guard rails and contextual information to get users going straight away. 

## Roles

| Role                | User
|---------------------|------------------------------
| Proposed by         | @kochie
| Author(s)           | @kochie
| API Bar Raiser      | @TheRealAmazonKendra 
| Stakeholders        | @alias, @alias, @alias

> See [RFC Process](https://github.com/aws/aws-cdk-rfcs#rfc-process) for details

## Workflow

- [x] Tracking issue created (label: `status/proposed`)
- [x] API bar raiser assigned (ping us at [#aws-cdk-rfcs](https://cdk-dev.slack.com/archives/C025ZFGMUCD) if needed)
- [x] Kick off meeting
- [x] RFC pull request submitted (label: `status/review`)
- [x] Community reach out (via Slack and/or Twitter)
- [ ] API signed-off (label `api-approved` applied to pull request)
- [ ] Final comments period (label: `status/final-comments-period`)
- [ ] Approved and merged (label: `status/approved`)
- [ ] Execution plan submitted (label: `status/planning`)
- [ ] Plan approved and merged (label: `status/implementing`)
- [ ] Implementation complete (label: `status/done`)

---

> Author is responsible to progress the RFC according to this checklist, and
apply the relevant labels to this issue so that the RFC table in README gets
updated.

**Comment by kochie** [comment]
I've just published the RFC as a PR. Anyone interested please feel free to contribute.

**Comment by awsmjs** [comment]
Closing this ticket. We believe the functionality is beneficial, but does not intersect with the core framework and should be vended and maintained separately.
