### ISSUE TITLE
L2 ElastiCache support

### ISSUE THREAD

**Issue by dbartholomae** [aws/aws-cdk-rfcs#456]
## Description

Adding a first L2 construct for ElastiCache ReplicationGroups which will take care of SubnetGroups as well.

## Roles

| Role                | User
|---------------------|------------------------------
| Proposed by         | @dbartholomae
| Author(s)           | @dbartholomae
| API Bar Raiser      | @corymhall 
| Stakeholders        | not yet decided

> See [RFC Process](https://github.com/aws/aws-cdk-rfcs#rfc-process) for details

## Workflow

- [x] Tracking issue created (label: `status/proposed`)
- [x] API bar raiser assigned (ping us at [#aws-cdk-rfcs](https://cdk-dev.slack.com/archives/C025ZFGMUCD) if needed)
- [x] Kick off meeting
- [x] RFC pull request submitted (label: `status/review`)
- [x] Community reach out (via Slack and/or Twitter)
- [x] API signed-off (label `api-approved` applied to pull request)
- [x] Final comments period (label: `status/final-comments-period`)
- [x] Approved and merged (label: `status/approved`)
- [x] Execution plan submitted (label: `status/planning`)
- [x] Plan approved and merged (label: `status/implementing`)
- [ ] Implementation complete (label: `status/done`)

---

> Author is responsible to progress the RFC according to this checklist, and
apply the relevant labels to this issue so that the RFC table in README gets
updated.

**Comment by dbartholomae** [comment]
Added @corymhall as API bar raiser

**Comment by dbartholomae** [comment]
@corymhall 
Sooo - if I understand correctly, the next step is an execution plan? Or can I just go at implementing parts and create a PR for the aws cdk repo?
We didn't actually add all the labels that are shown in the first comment in this thread in the check list, so if I need to add some of those, please let me know as well.

**Comment by corymhall** [comment]
@dbartholomae we can move right into implementing.

**Comment by awsmjs** [comment]
Closing this ticket. We believe the functionality is beneficial, but does not intersect with the core framework and should be vended and maintained separately.

**Comment by mrgrain** [comment]
Note: Added `status/rejected` to reflect the previous product decision. As far as I can tell the RFC itself is in good state and probably just needs a minor revision if CDK team were to re-prioritize this.
