### ISSUE TITLE
Amazon Aurora Serverless v2 support

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk-rfcs#470]
## Description

Amazon Aurora Serverless v2 has been [general available](https://aws.amazon.com/about-aws/whats-new/2022/04/amazon-aurora-serverless-v2/) since April 2022 and this feature has become one of the most popular features from the community. This RFC aims to provide a developer-friendly design as an addition to the existing L2 constructs of aws-rds that allows users to easily add serverless v2 instances to a new or existing clusters.

## Roles

| Role                | User
|---------------------|------------------------------
| Proposed by         | @pahud 
| Author(s)           | @pahud 
| API Bar Raiser      | @vinayak-kukreja
| Stakeholders        | @alias, @alias, @alias

> See [RFC Process](https://github.com/aws/aws-cdk-rfcs#rfc-process) for details

## Workflow

- [x] Tracking issue created (label: `status/proposed`)
- [x] API bar raiser assigned (ping us at [#aws-cdk-rfcs](https://cdk-dev.slack.com/archives/C025ZFGMUCD) if needed)
- [x] Kick off meeting
- [ ] RFC pull request submitted (label: `status/review`)
- [ ] Community reach out (via Slack and/or Twitter)
- [ ] API signed-off (label `api-approved` applied to pull request)
- [ ] Final comments period (label: `status/final-comments-period`)
- [ ] Approved and merged (label: `status/approved`)
- [ ] Execution plan submitted (label: `status/planning`)
- [ ] Plan approved and merged (label: `status/implementing`)
- [ ] Implementation complete (label: `status/done`)

---

> Author is responsible to progress the RFC according to this checklist, and
apply the relevant labels to this issue so that the RFC table in README gets
updated.

**Comment by lielran** [comment]
Thanks all 😊
