### ISSUE TITLE
New L2 Construct for Step Functions Map State in Distributed Mode

### ISSUE THREAD

**Issue by beck3905** [aws/aws-cdk-rfcs#487]
## Description

Step Functions recently released capabilities for a `Map` state in `DISTRIBUTED` mode.  This new capability comes with several new complex parameters.  It seems that adding those parameters as options to the existing `Map` state construct would result in a pretty complicated UX.  So I propose creating a new L2 construct with several supporting classes and interfaces for the various parameters of a `Map` state in `DISTRIBUTED` mode.  This L2 construct would extend the existing `Map` L2 construct.

## Roles

| Role                | User
|---------------------|------------------------------
| Proposed by         | @beck3905
| Author(s)           | @beck3905
| API Bar Raiser      | @MrArnoldPalmer 
| Stakeholders        | @alias, @alias, @alias

> See [RFC Process](https://github.com/aws/aws-cdk-rfcs#rfc-process) for details

## Workflow

- [x] Tracking issue created (label: `status/proposed`)
- [x] API bar raiser assigned (ping us at [#aws-cdk-rfcs](https://cdk-dev.slack.com/archives/C025ZFGMUCD) if needed)
- [ ] Kick off meeting
- [x] RFC pull request submitted (label: `status/review`)
- [ ] Community reach out (via Slack and/or Twitter)
- [ ] API signed-off (label `api-approved` applied to pull request)
- [ ] Final comments period (label: `status/final-comments-period`)
- [ ] Approved and merged (label: `status/approved`)
- [ ] Execution plan submitted (label: `status/planning`)
- [ ] Plan approved and merged (label: `status/implementing`)
- [ ] Implementation complete (label: `status/done`)

---

> Author is responsible to progress the RFC according to this checklist, and
apply the relevant labels to this issue so that the RFC table in README gets
updated.

**Comment by mrpackethead** [comment]
@evgenyka , who is the bar-raiser?

**Comment by MrArnoldPalmer** [comment]
@mrpackethead I am, taking a look at the proposal.

**Comment by awsmjs** [comment]
Closing this ticket. We believe the functionality is beneficial, but does not intersect with the core framework and should be vended and maintained separately.
