### ISSUE TITLE
AppConfig L2 Constructs

### ISSUE THREAD

**Issue by chenjane-dev** [aws/aws-cdk-rfcs#499]
## Description

Creating L2 constructs for AppConfig. There already is a tracking issue here (https://github.com/aws/aws-cdk/issues/6831) that has +1s and there was a previous issue for it (https://github.com/aws/aws-cdk-rfcs/issues/426) but seems to be abandoned now.

## Roles

| Role                | User
|---------------------|------------------------------
| Proposed by         | @chenjane-dev
| Author(s)              | @alias, @alias, @alias
| API Bar Raiser      | @otaviomacedo 
| Stakeholders        | @alias, @alias, @alias

> See [RFC Process](https://github.com/aws/aws-cdk-rfcs#rfc-process) for details

## Workflow

- [x] Tracking issue created (label: `status/proposed`)
- [x] API bar raiser assigned (ping us at [#aws-cdk-rfcs](https://cdk-dev.slack.com/archives/C025ZFGMUCD) if needed)
- [x] Kick off meeting
- [x] RFC pull request submitted (label: `status/review`)
- [x] Community reach out (via Slack and/or Twitter)
- [x] API signed-off (label `api-approved` applied to pull request)
- [x] Final comments period (label: `status/final-comments-period`)
- [x] Approved and merged (label: `status/approved`)
- [x] Execution plan submitted (label: `status/planning`)
- [ ] Plan approved and merged (label: `status/implementing`)
- [ ] Implementation complete (label: `status/done`)

---

> Author is responsible to progress the RFC according to this checklist, and
apply the relevant labels to this issue so that the RFC table in README gets
updated.

**Comment by awsmjs** [comment]
Closing this ticket. We believe the functionality is beneficial, but does not intersect with the core framework and should be vended and maintained separately.
