### ISSUE TITLE
Full control over VPC and subnet configuration

### ISSUE THREAD

**Issue by otaviomacedo** [aws/aws-cdk-rfcs#507]
## Description

New L2 constructs to allow for greater control over subnet configuration. There are a number of use cases that are not supported by the `Vpc` construct.

See https://github.com/aws/aws-cdk/issues/5927 for more details.

## Roles

| Role                | User
|---------------------|------------------------------
| Proposed by         | @otaviomacedo
| Author(s)           | @otaviomacedo 
| API Bar Raiser      | @corymhall 
| Stakeholders        | @udaypant, @evgenyka

> See [RFC Process](https://github.com/aws/aws-cdk-rfcs#rfc-process) for details

## Workflow

- [x] Tracking issue created (label: `status/proposed`)
- [x] API bar raiser assigned (ping us at [#aws-cdk-rfcs](https://cdk-dev.slack.com/archives/C025ZFGMUCD) if needed)
- [x] Kick off meeting
- [x] RFC pull request submitted (label: `status/review`)
- [x] Community reach out (via Slack and/or Twitter)
- [x] API signed-off (label `api-approved` applied to pull request)
- [x] Final comments period (label: `status/final-comments-period`)
- [x] Approved and merged (label: `status/approved`)
- [ ] Execution plan submitted (label: `status/planning`)
- [ ] Plan approved and merged (label: `status/implementing`)
- [ ] Implementation complete (label: `status/done`)

---

> Author is responsible to progress the RFC according to this checklist, and
apply the relevant labels to this issue so that the RFC table in README gets
updated.
