### ISSUE TITLE
DyanmoDB Global Table L2 Construct

### ISSUE THREAD

**Issue by vinayak-kukreja** [aws/aws-cdk-rfcs#510]
## Description

DynamoDB Global Table lets the user to create a table that can be replicated to other regions. An update to any of the replicas is propagated to other replicas. This enhances availability and reduces latency to write/access table data from different regions.
This feature would enable customers to use an L2 to provision Global Table with CDK. 

## Roles

| Role                | User
|---------------------|------------------------------
| Proposed by         | @vinayak-kukreja 
| Author(s)           | @vinayak-kukreja 
| API Bar Raiser      | @rix0rrr 
| Stakeholders        | @aws/aws-cdk-team 

> See [RFC Process](https://github.com/aws/aws-cdk-rfcs#rfc-process) for details

## Workflow

- [x] Tracking issue created (label: `status/proposed`)
- [x] API bar raiser assigned (ping us at [#aws-cdk-rfcs](https://cdk-dev.slack.com/archives/C025ZFGMUCD) if needed)
- [x] Kick off meeting
- [x] RFC pull request submitted (label: `status/review`)
- [x] Community reach out (via Slack and/or Twitter)
- [x] API signed-off (label `api-approved` applied to pull request)
- [x] Final comments period (label: `status/final-comments-period`)
- [x] Approved and merged (label: `status/approved`)
- [ ] Execution plan submitted (label: `status/planning`)
- [ ] Plan approved and merged (label: `status/implementing`)
- [ ] Implementation complete (label: `status/done`)

---

> Author is responsible to progress the RFC according to this checklist, and
apply the relevant labels to this issue so that the RFC table in README gets
updated.
