### ISSUE TITLE
Feature Flags

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#55]
|PR|Champion|
|--|--------|
|#56 | @eladb         |

## Description

Sometimes we want to introduce new breaking behavior because we believe this is
the correct default behavior for the CDK. The problem, of course, is that
breaking changes are only allowed in major versions and those are rare.

Feature flags are a pattern/mechanism which will allow us to introduce breaking behavior which is disabled by default (so existing projects will not be affected) but enabled automatically for new
projects created through `cdk init`.

## Progress

- [x] Tracking Issue Created
- [x] RFC PR Created 
- [x] Core Team Member Assigned: @eladb
- [x] Initial Approval / Final Comment Period
- [x] Ready For Implementation
    
    - [x] Implement first feature flag (https://github.com/aws/aws-cdk/pull/4925)
    - [x] Update developer guide to describe feature flags: https://github.com/awsdocs/aws-cdk-guide/issues/162
    - [x] Add feature flags to `cdk doctor` and update issue template (https://github.com/aws/aws-cdk/issues/5627)
- [x] Resolved
