### ISSUE TITLE
Bazel Build System

### ISSUE THREAD

**Issue by CaerusKaru** [aws/aws-cdk-rfcs#60]
|PR|Champion|
|--|--------|
|#61|  eladb      |

Originally posted here: aws/aws-cdk#5799

## Description

Migrate from Lerna and bash scripts to Bazel as the build system for the CDK.

## Progress

- [x] Tracking Issue Created
- [x] RFC PR Created 
- [x] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved 

Supersedes #48
