### ISSUE TITLE
CDK v2.0

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#79]
|PR|Champion|
|--|--------|
|#156 |  @eladb       |

## Description

Proposal detailing how we release aws-cdk 2.0 and how we want to handle major versions in the future.

### Things to consider

- [ ] Release process
- [ ] Long-term support for previous major versions
- [ ] Regular clean ups across major versions such as:
  - [ ] Remove all deprecated APIs
  - [ ] Reset all [feature flags](https://github.com/aws/aws-cdk/blob/master/design/feature-flags.md)

#### Required

- [Monocdk](https://github.com/aws/aws-cdk-rfcs/issues/6)
- Reset Feature Flags
- Remove All Deprecations

#### Recommended

- [Easier Identification of Experimental Modules and APIs](https://github.com/aws/aws-cdk-rfcs/issues/116)
- [Public S3 Artifacts](https://github.com/aws/aws-cdk-rfcs/issues/39)
- [Rename ID Parameter](https://github.com/aws/aws-cdk/issues/3203)
- Remove all usage of Type unions

#### Not Recommended

- [Unmangled L2 Logical IDs](https://github.com/aws/aws-cdk/issues/1687)
- [Removal of All Union Types](https://github.com/aws/aws-cdk/issues/5067)
- [Remove Custom Resource Implementation of Fargate Event Target](https://github.com/aws/aws-cdk/issues/3930)
- [Change Logical IDs to Avoid Potential Collisions](https://github.com/aws/aws-cdk/issues/6421)
- [Replace `addToPolicy` with `addTo{Principal,Identity}Policy`](https://github.com/aws/aws-cdk/pull/7598)

#### More Info Needed

- [AliasOptions and VersionOptions should not extend EventInvokeConfigOptions](https://github.com/aws/aws-cdk/issues/6966)
- [Remove Support for Docker Assets with Parameters]()

## Progress

- [x] Tracking Issue Created
- [x] RFC PR Created 
- [x] Core Team Member Assigned 
- [x] Initial Approval / Final Comment Period
- [x] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by eladb** [comment]
Closing this in favor of #118

**Comment by flemjame-at-amazon** [comment]
How can we make suggestions for things to consider for CDK v2.0? Open an issue?

**Comment by MrArnoldPalmer** [comment]
> How can we make suggestions for things to consider for CDK v2.0? Open an issue?

Comment on the tracking issue with your suggestions pls. #79

**Comment by flemjame-at-amazon** [comment]
One of AWS's core tenets is to be secure, and many constructs have defaults that are overly permissive. I propose changing construct defaults to be more aligned with AWS defaults, or to be secure by default. 

Two examples off the top of my head are:

By default, VPC endpoints allow all traffic from the VPC (see the [open](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.InterfaceVpcEndpoint.html) parameter). When creating an endpoint in the console, by default no traffic is allowed. I would change this default to be "false".

By default, NetworkLoadBalancedFargate service is fully open to the public internet (see the [publicLoadBalancer](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs-patterns.NetworkLoadBalancedFargateService.html) parameter). I would change this to be false by default.

**Comment by mwfpope** [comment]
One of the well-architected tenets is cost optimization (and there's the Amazon LP of Frugality), so can we try to avoid having CDK create unnecessary resources?

Eg: By default, the L3 VPC construct creates an EIP for each AZ. The default limit is 5 EIPs. To deploy more than one VPC in the same region, you first need to request a quota increase. If you're using those VPCs for Lambda(s), then the EIPs will go unused. (And of course, EIPs are billed only if they are unused.) There seems to be no option in the L3 construct to not have EIPs for the VPC.

In a multi-region, microservice architecture, this could easily end up being hundreds of unused EIPs. Suppose we have a distributed system that consists of 10 microservices, each in their own VPC. Suppose for each microservices, we deploy 1 test instance, and a production instance in 4 regions, with 3 AZs per VPC. Now, we have 150 unused EIPs which will cumulatively cost over $500 per month.

It's possible to delete unnecessary resources (once you realize that they exist) using [this obscure and undocumented method](https://github.com/aws/aws-cdk/issues/1408#issuecomment-551628704-permalink), but in this case, a better solution might be to have no EIPs by default or to have different L3 VPC constructs for different purposes (ie. create a LambdaVPC that encompasses best practices for running a Lambda VPC).

I only have this one example, but I wouldn't have even noticed this example if I didn't run into the quota limit when I was trying to deploy multiple serverless applications to the same development account. It would be very easy for other instances of this problem to occur completely unnoticed until you dive deep into a bill at some point in the future.

**Comment by MrArnoldPalmer** [comment]
Adding https://github.com/aws/aws-cdk/issues/3763 to the radar of 2.0 since it involves replacing existing deployed constructs.

@SoManyHs
@pkandasamy91

**Comment by flemjame-at-amazon** [comment]
I have another suggestion for 2.0 -- replace the usage of "Subnets" with "SubnetMappings" for elastic load balancers. Currently the load balancer constructs use Subnets, which are just a list of IDs. Using SubnetMappings allows you to specify subnet IDs and also an  EIP or a private IPv4 address. However, you can't switch from Subnets to SubnetMappings without replacing the load balancer.

Relevant cloudformation - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html#cfn-elasticloadbalancingv2-loadbalancer-subnets

**Comment by GriffinMB** [comment]
Along the lines of what @flemjame-at-amazon said, it would be great if security-relevant properties either defaulted to a "most secure" setting, or, where the property may be availability or cost impacting, were required properties so developers could make a conscious decision about the setting.
