### ISSUE TITLE
CI/CD Asset Publishing

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#92]
|PR|Champion|
|--|--------|
|[#3437](https://github.com/aws/aws-cdk/pull/3437) |   @eladb     |

## Description

cdk-assets is a tool in the AWS CDK toolchain responsible to package and publish assets as part of the deployment process of CDK applications.

## Progress

- [x] Tracking Issue Created
- [x] RFC PR Created 
- [x] Core Team Member Assigned 
- [x] Initial Approval / Final Comment Period
- [x] Ready For Implementation
- [ ] Resolved

**Comment by zxkane** [comment]
How about also supporting one-click CloudFormation template in this theme? Another kind of template output with fixed asset information. See aws/aws-cdk#7860 for detail request.

**Comment by polothy** [comment]
Hey @eladb! Saw that this issue closed, does that mean it will be available soon or is there a way to preview/test CDK asset publishing?  Very excited!  Thanks to you and the CDK team!

**Comment by eladb** [comment]
Yes. @rix0rrr can offer some pointers

**Comment by polothy** [comment]
Hey @rix0rrr - any pointers or too early still?  Not sure if there is a preview of this feature we can try?  Sorry for the noise, just very excited for getting this feature 😄

**Comment by alexnikolis** [comment]
I believe this is the issue tracking the actual implementation of this feature: https://github.com/aws/aws-cdk/issues/1312

I am also very excited for this feature!
