### ISSUE TITLE
Cognito Construct Library

### ISSUE THREAD

**Issue by nija-at** [aws/aws-cdk-rfcs#95]
|PR|Champion|
|--|--------|
|#91 | @eladb |

## Description

Increase coverage of CDK construct library for Cognito to cover a lot more features than it currently does. Where necessary, re-design the APIs so they are more ergonomic and extendible.

## Progress

- [x] Tracking Issue Created
- [x] RFC PR Created 
- [x] Core Team Member Assigned 
- [x] Initial Approval / Final Comment Period
- [x] Ready For Implementation
    
    - [x] implement User Pool construct
    - [ ] implement UserPoolUser and UserPoolGroup constructs
    - [ ] implement IdentityPool & IdentityPoolRoleAttachment constructs
    - [ ] open issues to track unimplemented features
- [ ] Resolved

**Comment by 0xdevalias** [comment]
Curious if there is a current ETA on these features landing/if they are actively being worked on at the moment?

**Comment by nija-at** [comment]
Some of these have started landing - https://github.com/aws/aws-cdk/commits/master/packages/%40aws-cdk/aws-cognito/lib, however, we don't have an ETA.

Is there a particular feature you're looking for?

**Comment by 0xdevalias** [comment]
I'm basically looking to setup a new cognito auth stack, custom domain, some federated logins, attach some custom lambda hooks, etc.

I saw the cognito construct features that landed very recently, but haven't incorporated those yet. So far i've been working around with everything else as required at the `Cfn*` CloudFormation level + using escape hatches.

Another issue I have just run into (though it's a CloudFormation deficiency, so beyond the scope of CDK, unless you were to roll a custom resource to resolve it) is that it's not currently possible to retrieve the CloudFront target when setting a custom domain, as per https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/356

**Comment by 0xdevalias** [comment]
<details><summary>Using a custom domain name with UserPool example</summary>

```javascript
/**
 * Configures the UserPool domain used for authentication.
 *
 * @see https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cognito.CfnUserPoolDomain.html
 * @see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpooldomain.html
 * @see https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-assign-domain.html
 */
const userPoolDomain = new cognito.CfnUserPoolDomain(
  this,
  'UserPoolDomain',
  {
    userPoolId: userPool.userPoolId,
    domain: authDomain,
    customDomainConfig: {
      certificateArn,
    },
  }
)
userPoolDomain.node.addDependency(userPool)
new cdk.CfnOutput(this, 'UserPoolDomainValue', {
  value: userPoolDomain.domain,
})

// https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#describeUserPoolDomain-property
const describeCognitoUserPoolDomain = new cr.AwsCustomResource(
  this,
  'DescribeCognitoUserPoolDomain',
  {
    resourceType: 'Custom::DescribeCognitoUserPoolDomain',
    onCreate: {
      region: 'us-east-1',
      service: 'CognitoIdentityServiceProvider',
      action: 'describeUserPoolDomain',
      parameters: {
        Domain: userPoolDomain.domain,
      },
      physicalResourceId: cr.PhysicalResourceId.of(userPoolDomain.domain),
    },
    // TODO: can we restrict this policy more? Get the ARN for the user pool domain? Or the user pool maybe?
    policy: cr.AwsCustomResourcePolicy.fromSdkCalls({
      resources: cr.AwsCustomResourcePolicy.ANY_RESOURCE,
    }),
  }
)
describeCognitoUserPoolDomain.node.addDependency(userPoolDomain)

const userPoolDomainDistribution = describeCognitoUserPoolDomain.getResponseField(
  'DomainDescription.CloudFrontDistribution'
)
new cdk.CfnOutput(this, 'UserPoolDomainDistribution', {
  value: userPoolDomainDistribution,
})

// Route53 alias record for the UserPoolDomain CloudFront distribution
new route53.ARecord(this, 'UserPoolDomainAliasRecord', {
  recordName: userPoolDomain.domain,
  target: route53.RecordTarget.fromValues(userPoolDomainDistribution),
  zone,
})
```

</details>

**Comment by 0xdevalias** [comment]
Errors I have hit:

```
 1/3 | 8:50:23 PM | UPDATE_FAILED        | AWS::Cognito::UserPool                | UserPool (UserPool6BA7E5F2) The message is invalid. (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException; Request ID: c3ce01b4-a431-4475-82fd-fdc30fec3660)
	new UserPool (/Users/devalias/dev/REDACTED/packages/REDACTED-infrastructure/node_modules/@aws-cdk/aws-cognito/lib/user-pool.js:73:26)
```

```javascript
const userPool = new cognito.UserPool(this, 'UserPool', {
  // ..snip..

  userVerification: {
    emailSubject: 'Confirm your account on REDACTED',
    emailBody:
      'Hello {username}, welcome to REDACTED! Use the following link to verify your account: {####}',
    emailStyle: cognito.VerificationEmailStyle.LINK,
    smsMessage:
      'Hello {username}, welcome to REDACTED! Use the following code to verify your account: {####}',
  },

  // ..snip..
})
```

**Comment by nija-at** [comment]
Please continue tracking progress on Cognito here - https://github.com/aws/aws-cdk/issues/6765

Resolving this issue.
